
DROP TABLE IF EXISTS Test_instance;
DROP TABLE IF EXISTS Test;
DROP TABLE IF EXISTS Treatment;
DROP TABLE IF EXISTS Stay;
DROP TABLE IF EXISTS Prescribes_Medication;
DROP TABLE IF EXISTS Appointment;
DROP TABLE IF EXISTS Medication;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Affiliated_with;
DROP TABLE IF EXISTS Treatment_Description;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Slot;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS Physician;
DROP TABLE IF EXISTS Database_administrator;
DROP TABLE IF EXISTS Data_entry_operator;
DROP TABLE IF EXISTS Front_desk_operator;
DROP TABLE IF EXISTS User;


